import { jsPDF } from 'jspdf';
import type {
  Aircraft,
  FaultPrediction,
  WorkOrder,
  SparePart,
  ProcurementOrder,
  MockUser,
  FleetTrendPoint,
} from '@/data/types';
import { fmtDate, hoursToHuman } from '@/utils/helpers';
import { fleetAverageHealth } from '@/utils/healthCalculator';

/* ============================================================
   PDF report generator — jsPDF, minimal white design
   Note: jsPDF core fonts lack the ₹ glyph, so we use "Rs."
   ============================================================ */

const NAVY: [number, number, number] = [27, 43, 75];
const GREY: [number, number, number] = [110, 118, 135];
const LIGHT: [number, number, number] = [245, 246, 250];
const LINE: [number, number, number] = [226, 229, 238];

interface Ctx {
  doc: jsPDF;
  y: number;
  user: MockUser;
  title: string;
}

function pageWidth(doc: jsPDF) {
  return doc.internal.pageSize.getWidth();
}

function drawHeader(ctx: Ctx) {
  const { doc } = ctx;
  const W = pageWidth(doc);
  // top rule
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(1.2);
  doc.line(40, 46, W - 40, 46);
  // logo mark
  doc.setFillColor(...NAVY);
  doc.roundedRect(40, 16, 12, 12, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('V', 44.4, 24.6);
  // wordmark
  doc.setTextColor(...NAVY);
  doc.setFontSize(15);
  doc.text('Vayu Sewa', 58, 26);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...GREY);
  doc.text('Predictive Maintenance & Fleet Intelligence', 58, 32);
  // meta right
  doc.setFontSize(8);
  doc.text(`Generated: ${new Date().toLocaleString('en-IN')}`, W - 40, 22, { align: 'right' });
  doc.text(`Generated by: ${ctx.user.name}`, W - 40, 28, { align: 'right' });
  // title
  doc.setTextColor(...NAVY);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.text(ctx.title, 40, 60);
  ctx.y = 70;
}

function drawFooter(ctx: Ctx) {
  const { doc } = ctx;
  const W = pageWidth(doc);
  const H = doc.internal.pageSize.getHeight();
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.5);
    doc.line(40, H - 30, W - 40, H - 30);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(...GREY);
    doc.text('Vayu Sewa — Restricted: For official use only', 40, H - 20);
    doc.text(`Page ${i} of ${pages}`, W - 40, H - 20, { align: 'right' });
  }
}

interface Column {
  header: string;
  width: number;
  key: string;
  align?: 'left' | 'right' | 'center';
  format?: (row: Record<string, unknown>, index: number) => string;
}

function drawTable(ctx: Ctx, columns: Column[], rows: Record<string, unknown>[]) {
  const { doc } = ctx;
  const W = pageWidth(doc);
  const x0 = 40;
  const usable = W - 80;
  const totalW = columns.reduce((s, c) => s + c.width, 0);
  const scale = usable / totalW;

  const rowH = 13;
  const ensureSpace = (needed: number) => {
    const H = doc.internal.pageSize.getHeight();
    if (ctx.y + needed > H - 40) {
      doc.addPage();
      ctx.y = 50;
      renderHeaderRow();
    }
  };

  const renderHeaderRow = () => {
    doc.setFillColor(...NAVY);
    doc.rect(x0, ctx.y, usable, rowH, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(8);
    let x = x0;
    columns.forEach((c) => {
      const cw = c.width * scale;
      const tx = c.align === 'right' ? x + cw - 4 : c.align === 'center' ? x + cw / 2 : x + 4;
      doc.text(c.header, tx, ctx.y + 8.5, { align: c.align === 'right' ? 'right' : c.align === 'center' ? 'center' : 'left' });
      x += cw;
    });
    ctx.y += rowH;
  };

  renderHeaderRow();

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  rows.forEach((row, ri) => {
    ensureSpace(rowH);
    if (ri % 2 === 1) {
      doc.setFillColor(...LIGHT);
      doc.rect(x0, ctx.y, usable, rowH, 'F');
    }
    doc.setDrawColor(...LINE);
    doc.setLineWidth(0.2);
    doc.line(x0, ctx.y + rowH, x0 + usable, ctx.y + rowH);
    let x = x0;
    doc.setTextColor(40, 46, 60);
    columns.forEach((c) => {
      const cw = c.width * scale;
      const raw = c.format ? c.format(row, ri) : String(row[c.key] ?? '');
      const tx = c.align === 'right' ? x + cw - 4 : c.align === 'center' ? x + cw / 2 : x + 4;
      doc.text(doc.splitTextToSize(raw, cw - 8)[0] ?? '', tx, ctx.y + 8.5, {
        align: c.align === 'right' ? 'right' : c.align === 'center' ? 'center' : 'left',
      });
      x += cw;
    });
    ctx.y += rowH;
  });
  ctx.y += 14;
}

function drawStatChips(ctx: Ctx, chips: { label: string; value: string }[]) {
  const { doc } = ctx;
  const W = pageWidth(doc);
  const chipW = (W - 80 - (chips.length - 1) * 8) / chips.length;
  const chipH = 24;
  chips.forEach((chip, i) => {
    const x = 40 + i * (chipW + 8);
    doc.setFillColor(...LIGHT);
    doc.setDrawColor(...LINE);
    doc.roundedRect(x, ctx.y, chipW, chipH, 2, 2, 'FD');
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(...NAVY);
    doc.text(chip.value, x + 6, ctx.y + 11);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(...GREY);
    doc.text(chip.label.toUpperCase(), x + 6, ctx.y + 18.5);
  });
  ctx.y += chipH + 14;
}

function drawParagraph(ctx: Ctx, text: string) {
  const { doc } = ctx;
  const W = pageWidth(doc);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(40, 46, 60);
  const lines = doc.splitTextToSize(text, W - 80);
  doc.text(lines, 40, ctx.y);
  ctx.y += lines.length * 4.6 + 8;
}

function drawLineChart(ctx: Ctx, points: FleetTrendPoint[], h = 60) {
  const { doc } = ctx;
  const W = pageWidth(doc);
  const x0 = 45;
  const y0 = ctx.y;
  const cw = W - 90;
  const ch = h;
  // frame
  doc.setDrawColor(...LINE);
  doc.rect(x0, y0, cw, ch);
  // grid
  doc.setFontSize(7);
  doc.setTextColor(...GREY);
  [0, 25, 50, 75, 100].forEach((v) => {
    const yy = y0 + ch - (v / 100) * ch;
    doc.line(x0, yy, x0 + cw, yy);
    doc.text(String(v), x0 - 4, yy + 2, { align: 'right' });
  });
  // line
  doc.setDrawColor(...NAVY);
  doc.setLineWidth(1);
  const px = (i: number) => x0 + (i / (points.length - 1)) * cw;
  const py = (v: number) => y0 + ch - (v / 100) * ch;
  for (let i = 1; i < points.length; i++) {
    doc.line(px(i - 1), py(points[i - 1].health), px(i), py(points[i].health));
  }
  // last point marker
  const last = points[points.length - 1];
  doc.setFillColor(...NAVY);
  doc.circle(px(points.length - 1), py(last.health), 1.6, 'F');
  ctx.y += ch + 14;
}

function newDoc(ctx: Ctx): jsPDF {
  ctx.doc.addPage();
  return ctx.doc;
}

/* ============================================================
   Report builders
   ============================================================ */

function baseDoc(title: string, user: MockUser): Ctx {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const ctx: Ctx = { doc, y: 70, user, title };
  drawHeader(ctx);
  return ctx;
}

function finish(ctx: Ctx, filename: string) {
  drawFooter(ctx);
  ctx.doc.save(filename);
}

export function generateFleetHealthPDF(
  aircraft: Aircraft[],
  predictions: FaultPrediction[],
  trend: FleetTrendPoint[],
  user: MockUser
) {
  const ctx = baseDoc('Fleet Health Summary Report', user);
  const { doc } = ctx;

  const operational = aircraft.filter((a) => a.status === 'operational').length;
  const maintenance = aircraft.filter((a) => a.status === 'maintenance').length;
  const criticalGrounded = aircraft.filter(
    (a) => a.status === 'critical' || a.status === 'grounded'
  ).length;

  drawStatChips(ctx, [
    { label: 'Total Aircraft', value: String(aircraft.length) },
    { label: 'Operational', value: String(operational) },
    { label: 'Under Maintenance', value: String(maintenance) },
    { label: 'Critical / Grounded', value: String(criticalGrounded) },
    { label: 'Fleet Health', value: `${fleetAverageHealth(aircraft)}%` },
  ]);

  drawParagraph(
    ctx,
    'This report consolidates fleet-wide health scores computed from weighted component health (Engine 40%, Hydraulic 20%, Avionics 20%, Landing Gear 10%, Fuel System 10%), live sensor telemetry and active fault predictions.'
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text('Fleet Health Trend — Last 30 Days', 40, ctx.y);
  ctx.y += 6;
  drawLineChart(ctx, trend);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Aircraft Status Detail', 40, ctx.y);
  ctx.y += 6;
  drawTable(
    ctx,
    [
      { header: 'Aircraft', width: 20, key: 'id' },
      { header: 'Name', width: 30, key: 'name' },
      { header: 'Type', width: 16, key: 'type' },
      { header: 'Health', width: 14, key: 'healthScore', align: 'right', format: (r) => `${r.healthScore}%` },
      { header: 'Status', width: 20, key: 'status' },
      { header: 'Flight Hrs', width: 16, key: 'flightHours', align: 'right' },
      { header: 'Last Maint.', width: 24, key: 'lastMaintenance', format: (r) => fmtDate(String(r.lastMaintenance)) },
    ],
    aircraft.map((a) => ({ ...a }) as unknown as Record<string, unknown>)
  );

  doc.addPage();
  ctx.y = 50;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text('Active Critical Alerts', 40, ctx.y);
  ctx.y += 6;
  const crit = predictions
    .slice()
    .sort((a, b) => a.estimatedFailureHours - b.estimatedFailureHours)
    .slice(0, 12);
  drawTable(
    ctx,
    [
      { header: 'ID', width: 12, key: 'id' },
      { header: 'Aircraft', width: 16, key: 'aircraftId' },
      { header: 'Component', width: 34, key: 'component' },
      { header: 'Confidence', width: 18, key: 'confidence', align: 'right', format: (r) => `${r.confidence}%` },
      { header: 'Est. Failure', width: 22, key: 'estimatedFailureHours', align: 'right', format: (r) => hoursToHuman(Number(r.estimatedFailureHours)) },
      { header: 'Severity', width: 18, key: 'severity' },
      { header: 'Action', width: 60, key: 'recommendedAction' },
    ],
    crit as unknown as Record<string, unknown>[]
  );

  finish(ctx, `VayuSewa-FleetHealth-${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function generateReadinessPDF(
  aircraft: Aircraft[],
  predictions: FaultPrediction[],
  projection: { window: string; ready: number; note: string }[],
  user: MockUser
) {
  const ctx = baseDoc('Mission Readiness Report', user);
  const { doc } = ctx;

  const readyAircraft = aircraft.filter(
    (a) => a.status === 'operational' && !predictions.some((p) => p.aircraftId === a.id && p.severity === 'critical')
  );

  drawStatChips(ctx, [
    { label: 'Mission Ready Now', value: String(readyAircraft.length) },
    { label: 'Total Fleet', value: String(aircraft.length) },
    { label: 'Readiness Rate', value: `${Math.round((readyAircraft.length / aircraft.length) * 100)}%` },
  ]);

  drawParagraph(
    ctx,
    'Mission-ready aircraft are operational platforms without an active critical fault prediction. Projected availability accounts for scheduled maintenance completion and remaining work-order hours.'
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text('Projected Readiness Timeline', 40, ctx.y);
  ctx.y += 6;
  drawTable(
    ctx,
    [
      { header: 'Window', width: 30, key: 'window' },
      { header: 'Aircraft Ready', width: 26, key: 'ready', align: 'right' },
      { header: 'Notes', width: 80, key: 'note' },
    ],
    projection as unknown as Record<string, unknown>[]
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Ready Aircraft List', 40, ctx.y);
  ctx.y += 6;
  drawTable(
    ctx,
    [
      { header: 'Aircraft', width: 20, key: 'id' },
      { header: 'Name', width: 34, key: 'name' },
      { header: 'Type', width: 20, key: 'type' },
      { header: 'Health', width: 16, key: 'healthScore', align: 'right', format: (r) => `${r.healthScore}%` },
      { header: 'Squadron', width: 30, key: 'squadron' },
      { header: 'Base', width: 30, key: 'base' },
    ],
    readyAircraft as unknown as Record<string, unknown>[]
  );

  finish(ctx, `VayuSewa-Readiness-${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function generateSchedulePDF(workOrders: WorkOrder[], user: MockUser) {
  const ctx = baseDoc('Maintenance Schedule — Next 30 Days', user);
  const inWindow = workOrders
    .filter((w) => w.status !== 'completed' && new Date(w.dueBy).getTime() < Date.now() + 30 * 86400000)
    .sort((a, b) => (a.dueBy > b.dueBy ? 1 : -1));

  drawParagraph(
    ctx,
    'Upcoming maintenance tasks across the fleet for the next 30 days, including predictive work orders raised from AI fault detection.'
  );

  drawTable(
    ctx,
    [
      { header: 'WO ID', width: 16, key: 'id' },
      { header: 'Aircraft', width: 16, key: 'aircraftId' },
      { header: 'Task', width: 62, key: 'task' },
      { header: 'Priority', width: 16, key: 'priority' },
      { header: 'Status', width: 20, key: 'status' },
      { header: 'Crew', width: 26, key: 'assignedCrew' },
      { header: 'Due', width: 22, key: 'dueBy', format: (r) => fmtDate(String(r.dueBy)) },
    ],
    inWindow as unknown as Record<string, unknown>[]
  );
  finish(ctx, `VayuSewa-Schedule-${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function generateInventoryPDF(parts: SparePart[], user: MockUser) {
  const ctx = baseDoc('Inventory Status Report', user);
  const inStock = parts.filter((p) => p.quantity > p.minimumRequired).length;
  const low = parts.filter((p) => p.quantity > 0 && p.quantity <= p.minimumRequired).length;
  const out = parts.filter((p) => p.quantity === 0).length;
  const value = parts.reduce((s, p) => s + p.quantity * p.unitCost, 0);

  drawStatChips(ctx, [
    { label: 'Total Line Items', value: String(parts.length) },
    { label: 'Healthy Stock', value: String(inStock) },
    { label: 'Low Stock', value: String(low) },
    { label: 'Out of Stock', value: String(out) },
    { label: 'Stock Value', value: `Rs. ${(value / 100000).toFixed(1)} L` },
  ]);

  drawTable(
    ctx,
    [
      { header: 'Part ID', width: 18, key: 'partId' },
      { header: 'Name', width: 44, key: 'name' },
      { header: 'Category', width: 20, key: 'category' },
      { header: 'Qty', width: 10, key: 'quantity', align: 'right' },
      { header: 'Min', width: 10, key: 'minimumRequired', align: 'right' },
      { header: 'Status', width: 22, key: 'quantity', format: (r) => (Number(r.quantity) === 0 ? 'Out of Stock' : Number(r.quantity) <= Number(r.minimumRequired) ? 'Low Stock' : 'In Stock') },
      { header: 'Location', width: 30, key: 'location' },
      { header: 'Restocked', width: 24, key: 'lastRestocked', format: (r) => fmtDate(String(r.lastRestocked)) },
    ],
    parts as unknown as Record<string, unknown>[]
  );
  finish(ctx, `VayuSewa-Inventory-${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function generateProcurementPDF(orders: ProcurementOrder[], user: MockUser) {
  const ctx = baseDoc('Procurement Summary Report', user);
  const open = orders.filter((o) => o.status !== 'received').length;
  const pipeline = orders.filter((o) => o.status !== 'received').reduce((s, o) => s + o.quantity * o.unitCost, 0);

  drawStatChips(ctx, [
    { label: 'Total Orders', value: String(orders.length) },
    { label: 'Open Orders', value: String(open) },
    { label: 'Pipeline Value', value: `Rs. ${(pipeline / 100000).toFixed(1)} L` },
  ]);

  drawTable(
    ctx,
    [
      { header: 'PO ID', width: 16, key: 'id' },
      { header: 'Part', width: 44, key: 'partName' },
      { header: 'Qty', width: 10, key: 'quantity', align: 'right' },
      { header: 'Status', width: 22, key: 'status' },
      { header: 'Supplier', width: 46, key: 'supplier' },
      { header: 'Expected', width: 24, key: 'expectedDelivery', format: (r) => fmtDate(String(r.expectedDelivery)) },
      { header: 'Value', width: 26, key: 'unitCost', align: 'right', format: (r) => `Rs. ${((Number(r.unitCost) * Number(r.quantity)) / 100000).toFixed(1)} L` },
    ],
    orders as unknown as Record<string, unknown>[]
  );
  finish(ctx, `VayuSewa-Procurement-${new Date().toISOString().slice(0, 10)}.pdf`);
}

export function generateConsumptionPDF(
  topParts: { part: string; usage: number }[],
  monthly: { month: string; cost: number }[],
  user: MockUser
) {
  const ctx = baseDoc('Parts Consumption Report', user);
  const { doc } = ctx;
  drawParagraph(
    ctx,
    'Consumption analytics across the last 6 months. High-usage consumables are the primary cost drivers; lead-time on these items drives most stock-out risk.'
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(...NAVY);
  doc.text('Top Consumed Parts', 40, ctx.y);
  ctx.y += 6;
  drawTable(
    ctx,
    [
      { header: '#', width: 8, key: 'idx', format: (_r, i) => String((i ?? 0) + 1) },
      { header: 'Part', width: 70, key: 'part' },
      { header: 'Units Consumed (6 mo)', width: 40, key: 'usage', align: 'right' },
    ],
    topParts as unknown as Record<string, unknown>[]
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Monthly Consumption Cost', 40, ctx.y);
  ctx.y += 6;
  drawTable(
    ctx,
    [
      { header: 'Month', width: 30, key: 'month' },
      { header: 'Cost (Rs.)', width: 40, key: 'cost', align: 'right', format: (r) => Number(r.cost).toLocaleString('en-IN') },
    ],
    monthly as unknown as Record<string, unknown>[]
  );
  finish(ctx, `VayuSewa-Consumption-${new Date().toISOString().slice(0, 10)}.pdf`);
}

/* ============================================================
   CSV export
   ============================================================ */

export function exportCSV(filename: string, columns: string[], rows: (string | number)[][]) {
  const esc = (v: string | number) => {
    const s = String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const csv = [columns.map(esc).join(','), ...rows.map((r) => r.map(esc).join(','))].join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(url), 2000);
}
