/* ============================================================
   Vayu Sewa — shared domain types
   ============================================================ */

export type Role = 'commander' | 'engineer' | 'logistics';

export type AircraftStatus =
  | 'operational'
  | 'warning'
  | 'critical'
  | 'maintenance'
  | 'grounded';

export type AircraftType = 'Fighter' | 'Transport' | 'Helicopter';

export type ComponentKey =
  | 'engine'
  | 'hydraulic'
  | 'avionics'
  | 'landingGear'
  | 'fuelSystem';

export type Severity = 'critical' | 'warning';
export type Priority = 'critical' | 'high' | 'medium' | 'low';
export type WOStatus = 'pending' | 'in-progress' | 'completed';
export type StockStatus = 'in-stock' | 'low-stock' | 'out-of-stock';
export type ProcurementStatus =
  | 'raised'
  | 'approved'
  | 'ordered'
  | 'in-transit'
  | 'received';

export interface MockUser {
  id: number;
  name: string;
  role: Role;
  username: string;
}

export interface ComponentHealthMap {
  engine: number;
  hydraulic: number;
  avionics: number;
  landingGear: number;
  fuelSystem: number;
}

export interface Aircraft {
  id: string;
  name: string;
  type: AircraftType;
  healthScore: number;
  status: AircraftStatus;
  lastMaintenance: string; // ISO date
  flightHours: number;
  engineCycles: number;
  components: ComponentHealthMap;
  squadron: string;
  base: string;
}

export interface SensorReading {
  aircraftId: string;
  timestamp: number;
  engineTemp: number;
  vibration: number;
  oilPressure: number;
  fuelFlow: number;
  engineCycles: number;
}

export type SensorMetric = 'engineTemp' | 'vibration' | 'oilPressure' | 'fuelFlow';

export interface FaultPrediction {
  id: string;
  aircraftId: string;
  component: string;
  componentKey: ComponentKey;
  confidence: number;
  estimatedFailureHours: number;
  severity: Severity;
  recommendedAction: string;
  detectedAt: string;
  detectedAtTs: number;
  partsRequired: string[];
  acknowledged?: boolean;
  autoGenerated?: boolean;
}

export interface WorkOrder {
  id: string;
  aircraftId: string;
  task: string;
  priority: Priority;
  status: WOStatus;
  assignedCrew: string;
  partsRequired: string[];
  estimatedHours: number;
  createdAt: string;
  dueBy: string;
  fromPredictionId?: string;
}

export interface SparePart {
  partId: string;
  name: string;
  category: 'Hydraulic' | 'Engine' | 'Avionics' | 'Structural';
  quantity: number;
  minimumRequired: number;
  unitCost: number;
  location: string;
  lastRestocked: string;
}

export interface CrewMember {
  id: number;
  name: string;
  rank: string;
  skill: string;
  currentAssignment: string;
  aircraftId: string | null;
  tasksToday: number;
  tasksAssigned: number;
  tasksCompleted: number;
  status: 'Available' | 'Busy';
}

export interface MaintenanceRecord {
  id: string;
  aircraftId: string;
  date: string;
  task: string;
  crew: string;
  durationHours: number;
  type: 'Scheduled Service' | 'Repair' | 'Inspection' | 'Component Replacement';
}

export interface ProcurementOrder {
  id: string;
  partId: string;
  partName: string;
  quantity: number;
  status: ProcurementStatus;
  raisedOn: string;
  orderedOn: string | null;
  expectedDelivery: string;
  supplier: string;
  unitCost: number;
  aircraftId?: string;
  workOrderId?: string;
  urgency: Severity;
}

export type NotificationType = 'alert' | 'warning' | 'success' | 'info';

export interface AppNotification {
  id: string;
  type: NotificationType;
  title: string;
  description: string;
  timestamp: number;
  read: boolean;
}

export interface FleetTrendPoint {
  date: string;
  health: number;
}

export interface Recommendation {
  id: string;
  aircraftId: string;
  component: string;
  componentKey: ComponentKey;
  recommendation: string;
  rationale: string;
  riskIfIgnored: string;
  actNow: { downtimeHours: number; partsNeeded: number };
  wait: { downtimeHours: number; partsNeeded: number; missionImpact: string };
  predictionId: string;
}
